import { CheckCircle2, AlertTriangle, XCircle, Lightbulb, Sparkles, Target } from 'lucide-react'

const SCORE_TIERS = [
  { min: 85, label: 'Excellent', color: 'emerald' },
  { min: 70, label: 'Good',      color: 'blue'    },
  { min: 50, label: 'Average',   color: 'amber'   },
  { min: 0,  label: 'Needs Work', color: 'red'    },
]

const COLOR_STYLES = {
  emerald: {
    badge:  'border-emerald-200/70 bg-emerald-50 text-emerald-700 dark:border-emerald-800/40 dark:bg-emerald-950/40 dark:text-emerald-300',
    label:  'text-emerald-600 dark:text-emerald-400',
    wrap:   'border-emerald-200/50 bg-emerald-500/[0.04] dark:border-emerald-800/30 dark:bg-emerald-950/20',
    ring:   'stroke-emerald-500 dark:stroke-emerald-400',
  },
  blue: {
    badge:  'border-blue-200/70 bg-blue-50 text-blue-700 dark:border-blue-800/40 dark:bg-blue-950/40 dark:text-blue-300',
    label:  'text-blue-600 dark:text-blue-400',
    wrap:   'border-blue-200/50 bg-blue-500/[0.04] dark:border-blue-800/30 dark:bg-blue-950/20',
    ring:   'stroke-blue-500 dark:stroke-blue-400',
  },
  amber: {
    badge:  'border-amber-200/70 bg-amber-50 text-amber-700 dark:border-amber-800/40 dark:bg-amber-950/40 dark:text-amber-300',
    label:  'text-amber-600 dark:text-amber-400',
    wrap:   'border-amber-200/50 bg-amber-500/[0.04] dark:border-amber-800/30 dark:bg-amber-950/20',
    ring:   'stroke-amber-500 dark:stroke-amber-400',
  },
  red: {
    badge:  'border-red-200/70 bg-red-50 text-red-700 dark:border-red-800/40 dark:bg-red-950/40 dark:text-red-300',
    label:  'text-red-600 dark:text-red-400',
    wrap:   'border-red-200/50 bg-red-500/[0.04] dark:border-red-800/30 dark:bg-red-950/20',
    ring:   'stroke-red-500 dark:stroke-red-400',
  },
}

function ScoreRing({ score, ringClass }) {
  const radius = 32
  const circumference = 2 * Math.PI * radius
  const offset = circumference - (Math.min(100, Math.max(0, score)) / 100) * circumference

  return (
    <div className="relative flex h-[72px] w-[72px] shrink-0 items-center justify-center">
      <svg width="72" height="72" viewBox="0 0 72 72" className="-rotate-90">
        <circle
          cx="36"
          cy="36"
          r={radius}
          fill="none"
          strokeWidth="7"
          className="stroke-slate-200 dark:stroke-slate-700"
        />
        <circle
          cx="36"
          cy="36"
          r={radius}
          fill="none"
          strokeWidth="7"
          strokeLinecap="round"
          strokeDasharray={circumference}
          strokeDashoffset={offset}
          className={`transition-[stroke-dashoffset] duration-1000 ease-out ${ringClass}`}
        />
      </svg>
      <div className="absolute flex flex-col items-center">
        <span className="text-xl font-black leading-none">{score}</span>
        <span className="text-[9px] font-bold uppercase tracking-widest opacity-60">/100</span>
      </div>
    </div>
  )
}

function getScoreTier(score) {
  return SCORE_TIERS.find((t) => score >= t.min)
}

export default function AnalysisResult({ analysis }) {
  if (!analysis) return null

  const tier = getScoreTier(analysis.ats_score)
  const s = COLOR_STYLES[tier.color]

  return (
    <section className="rounded-2xl border border-slate-200/60 bg-white/90 p-6 shadow-xl backdrop-blur-xl sm:p-8 dark:border-white/[0.08] dark:bg-slate-900/80">
      {/* Header */}
      <div className="mb-6">
        <h2 className="text-lg font-bold tracking-tight text-slate-900 dark:text-slate-100">AI Resume Analysis</h2>
        <p className="mt-1 text-sm text-slate-500 dark:text-slate-400">
          Generated by Azure OpenAI GPT-4.1 via LangChain
        </p>
      </div>

      {/* ATS Score */}
      <div className={`mb-6 flex items-center gap-5 rounded-xl border px-5 py-4 ${s.wrap}`}>
        <div className={s.label}>
          <ScoreRing score={analysis.ats_score} ringClass={s.ring} />
        </div>
        <div>
          <p className={`text-xl font-bold ${s.label}`}>{tier.label}</p>
          <p className="text-sm text-slate-500 dark:text-slate-400">ATS Compatibility Score</p>
        </div>
      </div>

      {/* Professional Summary */}
      <div className="mb-6">
        <SectionHeader icon={Sparkles} title="Professional Summary" />
        <p className="mt-3 text-sm leading-relaxed text-slate-700 dark:text-slate-300">{analysis.summary}</p>
      </div>

      {/* Skills + Missing Skills */}
      <div className="mb-6 grid grid-cols-1 gap-4 sm:grid-cols-2">
        <div>
          <SectionHeader icon={Target} title="Key Skills" />
          <ChipList
            items={analysis.skills}
            chipClass="border-brand-200/70 bg-brand-50 text-brand-700 dark:border-brand-800/40 dark:bg-brand-950/40 dark:text-brand-300"
          />
        </div>
        <div>
          <SectionHeader icon={XCircle} title="Missing Skills" iconClass="text-red-500 dark:text-red-400" />
          <ChipList items={analysis.missing_skills} chipClass={s.badge} />
        </div>
      </div>

      {/* Strengths + Weaknesses */}
      <div className="mb-6 grid grid-cols-1 gap-4 sm:grid-cols-2">
        <div className="rounded-xl border border-emerald-200/50 bg-emerald-500/[0.04] p-4 dark:border-emerald-800/30 dark:bg-emerald-950/20">
          <SectionHeader icon={CheckCircle2} title="Strengths" iconClass="text-emerald-600 dark:text-emerald-400" />
          <BulletList
            items={analysis.strengths}
            icon={CheckCircle2}
            iconClass="text-emerald-500 dark:text-emerald-400"
          />
        </div>
        <div className="rounded-xl border border-amber-200/50 bg-amber-500/[0.04] p-4 dark:border-amber-800/30 dark:bg-amber-950/20">
          <SectionHeader icon={AlertTriangle} title="Weaknesses" iconClass="text-amber-600 dark:text-amber-400" />
          <BulletList
            items={analysis.weaknesses}
            icon={AlertTriangle}
            iconClass="text-amber-500 dark:text-amber-400"
          />
        </div>
      </div>

      {/* Suggestions */}
      <div>
        <SectionHeader icon={Lightbulb} title="Improvement Suggestions" iconClass="text-brand-600 dark:text-brand-400" />
        <ol className="mt-3 space-y-3">
          {analysis.suggestions.map((item, i) => (
            <li key={i} className="flex items-start gap-3 text-sm text-slate-700 dark:text-slate-300">
              <span className="flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-brand-500/10 text-[11px] font-black text-brand-600 dark:text-brand-400">
                {i + 1}
              </span>
              {item}
            </li>
          ))}
        </ol>
      </div>
    </section>
  )
}

function SectionHeader({ icon: Icon, title, iconClass = 'text-slate-500 dark:text-slate-400' }) {
  return (
    <div className="flex items-center gap-2">
      <Icon className={`h-4 w-4 shrink-0 ${iconClass}`} />
      <h3 className="text-xs font-bold uppercase tracking-widest text-slate-500 dark:text-slate-400">{title}</h3>
    </div>
  )
}

function ChipList({ items, chipClass }) {
  return (
    <div className="mt-3 flex flex-wrap gap-2">
      {items.map((item) => (
        <span
          key={item}
          className={`rounded-full border px-3 py-1 text-xs font-semibold ${chipClass}`}
        >
          {item}
        </span>
      ))}
    </div>
  )
}

function BulletList({ items, icon: Icon, iconClass }) {
  return (
    <ul className="mt-3 space-y-2">
      {items.map((item) => (
        <li key={item} className="flex items-start gap-2 text-sm text-slate-700 dark:text-slate-300">
          <Icon className={`mt-0.5 h-3.5 w-3.5 shrink-0 ${iconClass}`} />
          {item}
        </li>
      ))}
    </ul>
  )
}
