import { CheckCircle2, AlertTriangle, XCircle, Lightbulb, Sparkles, Target } from 'lucide-react'
import ChipList from './ChipList.jsx'
import ScoreRing, { COLOR_STYLES, getScoreTier } from './ScoreRing.jsx'

export default function AnalysisResult({ analysis, targetRole }) {
  if (!analysis) return null

  const tier = getScoreTier(analysis.ats_score)
  const s = COLOR_STYLES[tier.color]

  return (
    <section className="rounded-2xl border border-slate-200/60 bg-white/90 p-6 shadow-xl backdrop-blur-xl sm:p-8 dark:border-white/[0.08] dark:bg-slate-900/80">
      {/* Header */}
      <div className="mb-6 flex flex-wrap items-start justify-between gap-3">
        <div>
          <h2 className="text-lg font-bold tracking-tight text-slate-900 dark:text-slate-100">AI Resume Analysis</h2>
          <p className="mt-1 text-sm text-slate-500 dark:text-slate-400">
            Generated by Azure OpenAI GPT-4.1 via LangChain
          </p>
        </div>
        {targetRole && (
          <span className="inline-flex shrink-0 items-center gap-1.5 rounded-full border border-brand-300/70 bg-brand-100 px-3 py-1.5 text-xs font-bold text-brand-800 dark:border-brand-800/40 dark:bg-brand-950/40 dark:text-brand-300">
            <Target className="h-3.5 w-3.5" />
            Target Role: {targetRole}
          </span>
        )}
      </div>

      {/* ATS Score */}
      <div className={`mb-6 flex items-center gap-5 rounded-xl border px-5 py-4 ${s.wrap}`}>
        <div className={s.label}>
          <ScoreRing score={analysis.ats_score} ringClass={s.ring} />
        </div>
        <div>
          <p className={`text-xl font-bold ${s.label}`}>{tier.label}</p>
          <p className="text-sm text-slate-500 dark:text-slate-400">ATS Compatibility Score</p>
        </div>
      </div>

      {/* Professional Summary */}
      <div className="mb-6">
        <SectionHeader icon={Sparkles} title="Professional Summary" />
        <p className="mt-3 text-sm leading-relaxed text-slate-700 dark:text-slate-300">{analysis.summary}</p>
      </div>

      {/* Skills + Missing Skills */}
      <div className="mb-6 grid grid-cols-1 gap-4 sm:grid-cols-2">
        <div>
          <SectionHeader icon={Target} title="Key Skills" />
          <ChipList
            items={analysis.skills}
            chipClass="border-brand-300/70 bg-brand-100 text-brand-800 dark:border-brand-800/40 dark:bg-brand-950/40 dark:text-brand-300"
          />
        </div>
        <div>
          <SectionHeader icon={XCircle} title="Missing Skills" iconClass="text-red-500 dark:text-red-400" />
          <ChipList items={analysis.missing_skills} chipClass={s.badge} />
        </div>
      </div>

      {/* Strengths + Weaknesses */}
      <div className="mb-6 grid grid-cols-1 gap-4 sm:grid-cols-2">
        <div className="rounded-xl border border-emerald-200/50 bg-emerald-500/[0.04] p-4 dark:border-emerald-800/30 dark:bg-emerald-950/20">
          <SectionHeader icon={CheckCircle2} title="Strengths" iconClass="text-emerald-600 dark:text-emerald-400" />
          <BulletList
            items={analysis.strengths}
            icon={CheckCircle2}
            iconClass="text-emerald-500 dark:text-emerald-400"
          />
        </div>
        <div className="rounded-xl border border-amber-200/50 bg-amber-500/[0.04] p-4 dark:border-amber-800/30 dark:bg-amber-950/20">
          <SectionHeader icon={AlertTriangle} title="Weaknesses" iconClass="text-amber-600 dark:text-amber-400" />
          <BulletList
            items={analysis.weaknesses}
            icon={AlertTriangle}
            iconClass="text-amber-500 dark:text-amber-400"
          />
        </div>
      </div>

      {/* Suggestions */}
      <div>
        <SectionHeader icon={Lightbulb} title="Improvement Suggestions" iconClass="text-brand-600 dark:text-brand-400" />
        <ol className="mt-3 space-y-3">
          {analysis.suggestions.map((item, i) => (
            <li key={i} className="flex items-start gap-3 text-sm text-slate-700 dark:text-slate-300">
              <span className="flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-brand-500/10 text-[11px] font-black text-brand-600 dark:text-brand-400">
                {i + 1}
              </span>
              {item}
            </li>
          ))}
        </ol>
      </div>
    </section>
  )
}

function SectionHeader({ icon: Icon, title, iconClass = 'text-slate-500 dark:text-slate-400' }) {
  return (
    <div className="flex items-center gap-2">
      <Icon className={`h-4 w-4 shrink-0 ${iconClass}`} />
      <h3 className="text-xs font-bold uppercase tracking-widest text-slate-500 dark:text-slate-400">{title}</h3>
    </div>
  )
}

function BulletList({ items, icon: Icon, iconClass }) {
  return (
    <ul className="mt-3 space-y-2">
      {items.map((item) => (
        <li key={item} className="flex items-start gap-2 text-sm text-slate-700 dark:text-slate-300">
          <Icon className={`mt-0.5 h-3.5 w-3.5 shrink-0 ${iconClass}`} />
          {item}
        </li>
      ))}
    </ul>
  )
}
