import { useEffect, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { AlertTriangle, ArrowLeft, ArrowRight } from 'lucide-react'
import AnalysisResult from '../components/AnalysisResult.jsx'
import AnalysisSkeleton from '../components/AnalysisSkeleton.jsx'
import Stepper from '../components/Stepper.jsx'
import { analyzeResume } from '../api/client.js'

export default function AnalysisPage({ result, targetRole, analysis, onAnalysisComplete }) {
  const [error, setError] = useState(null)
  const [isLoading, setIsLoading] = useState(!analysis)
  const [retryCount, setRetryCount] = useState(0)
  const navigate = useNavigate()

  useEffect(() => {
    if (analysis) return
    let cancelled = false

    async function runAnalysis() {
      setIsLoading(true)
      setError(null)
      try {
        const { analysis: analysisData } = await analyzeResume(result.extracted_text, targetRole)
        if (!cancelled) onAnalysisComplete(analysisData)
      } catch (err) {
        if (cancelled) return
        let message
        if (err.response?.data?.detail) {
          message = err.response.data.detail
        } else if (!err.response && err.request) {
          message =
            'Could not reach the server. Open the browser console (F12) and look for the [API] log to see the exact error.'
        } else {
          message = 'Something went wrong. Please try again.'
        }
        setError(message)
      } finally {
        if (!cancelled) setIsLoading(false)
      }
    }

    runAnalysis()
    return () => {
      cancelled = true
    }
  }, [result, targetRole, analysis, onAnalysisComplete, retryCount])

  return (
    <>
      <button
        type="button"
        onClick={() => navigate('/')}
        className="mb-8 inline-flex items-center gap-1.5 text-sm font-semibold text-slate-500 transition-colors hover:text-brand-600 dark:text-slate-400 dark:hover:text-brand-400"
      >
        <ArrowLeft className="h-4 w-4" />
        Back to upload
      </button>

      <Stepper currentStep={2} />

      {/* Hero section */}
      <div className="mb-12 text-center">
        <h1 className="pb-1 text-4xl font-extrabold leading-tight tracking-tight sm:text-5xl bg-gradient-to-br from-slate-900 via-slate-700 to-slate-500 bg-clip-text text-transparent dark:from-white dark:via-slate-200 dark:to-slate-500">
          Your resume, analyzed
        </h1>
        <p className="mx-auto mt-4 max-w-xl text-sm leading-relaxed text-slate-500 dark:text-slate-400">
          ATS score, skill gaps, strengths, weaknesses, and actionable suggestions — generated by
          Azure OpenAI.
        </p>
      </div>

      <div className="flex flex-col gap-6">
        {isLoading && <AnalysisSkeleton />}

        {error && (
          <div className="flex items-start gap-3 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700 dark:border-red-900/50 dark:bg-red-950/30 dark:text-red-400">
            <AlertTriangle className="mt-0.5 h-4 w-4 shrink-0" />
            <span className="flex-1">{error}</span>
            <button
              type="button"
              onClick={() => setRetryCount((c) => c + 1)}
              className="shrink-0 font-semibold underline decoration-red-300 underline-offset-2 hover:decoration-red-500"
            >
              Try again
            </button>
          </div>
        )}

        <AnalysisResult analysis={analysis} targetRole={targetRole} />

        {analysis && (
          <div className="flex flex-col gap-3 sm:flex-row">
            <button
              type="button"
              onClick={() => navigate('/companies')}
              className="inline-flex w-full items-center justify-center gap-2 rounded-xl bg-gradient-to-r from-brand-600 to-accent-500 px-6 py-4 text-base font-bold text-white shadow-lg shadow-brand-500/25 transition-all hover:opacity-90 hover:shadow-brand-500/40"
            >
              Find Matching Companies
              <ArrowRight className="h-5 w-5" />
            </button>
            <button
              type="button"
              onClick={() => navigate('/toolkit')}
              className="inline-flex w-full items-center justify-center gap-2 rounded-xl border border-slate-200/60 bg-white/60 px-6 py-4 text-sm font-semibold text-slate-600 transition-colors hover:border-brand-300 hover:text-brand-600 dark:border-white/[0.08] dark:bg-slate-900/40 dark:text-slate-300 dark:hover:text-brand-400 sm:w-auto"
            >
              Explore Career Toolkit
              <ArrowRight className="h-4 w-4" />
            </button>
          </div>
        )}
      </div>
    </>
  )
}
