import { useEffect, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { AlertTriangle, ArrowLeft } from 'lucide-react'
import AnalysisResult from '../components/AnalysisResult.jsx'
import AnalysisSkeleton from '../components/AnalysisSkeleton.jsx'
import Stepper from '../components/Stepper.jsx'
import { analyzeResume } from '../api/client.js'

export default function AnalysisPage({ result }) {
  const [analysis, setAnalysis] = useState(null)
  const [error, setError] = useState(null)
  const [isLoading, setIsLoading] = useState(true)
  const navigate = useNavigate()

  useEffect(() => {
    let cancelled = false

    async function runAnalysis() {
      setIsLoading(true)
      setError(null)
      try {
        const { analysis: analysisData } = await analyzeResume(result.extracted_text)
        if (!cancelled) setAnalysis(analysisData)
      } catch (err) {
        if (cancelled) return
        let message
        if (err.response?.data?.detail) {
          message = err.response.data.detail
        } else if (!err.response && err.request) {
          message =
            'Could not reach the server. Open the browser console (F12) and look for the [API] log to see the exact error.'
        } else {
          message = 'Something went wrong. Please try again.'
        }
        setError(message)
      } finally {
        if (!cancelled) setIsLoading(false)
      }
    }

    runAnalysis()
    return () => {
      cancelled = true
    }
  }, [result])

  return (
    <>
      <button
        type="button"
        onClick={() => navigate('/')}
        className="mb-8 inline-flex items-center gap-1.5 text-sm font-semibold text-slate-500 transition-colors hover:text-brand-600 dark:text-slate-400 dark:hover:text-brand-400"
      >
        <ArrowLeft className="h-4 w-4" />
        Back to upload
      </button>

      <Stepper currentStep={2} />

      {/* Hero section */}
      <div className="mb-12 text-center">
        <h1 className="pb-1 text-4xl font-extrabold leading-tight tracking-tight sm:text-5xl bg-gradient-to-br from-slate-900 via-slate-700 to-slate-500 bg-clip-text text-transparent dark:from-white dark:via-slate-200 dark:to-slate-500">
          Your resume, analyzed
        </h1>
        <p className="mx-auto mt-4 max-w-xl text-sm leading-relaxed text-slate-500 dark:text-slate-400">
          ATS score, skill gaps, strengths, weaknesses, and actionable suggestions — generated by
          Azure OpenAI.
        </p>
      </div>

      <div className="flex flex-col gap-6">
        {isLoading && <AnalysisSkeleton />}

        {error && (
          <div className="flex items-start gap-3 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700 dark:border-red-900/50 dark:bg-red-950/30 dark:text-red-400">
            <AlertTriangle className="mt-0.5 h-4 w-4 shrink-0" />
            <span>{error}</span>
          </div>
        )}

        <AnalysisResult analysis={analysis} />
      </div>
    </>
  )
}
